// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPwXMkbbbLjH6iGf7w18yi0eGU5NDb1YY',
    appId: '1:826399227870:web:07aeb871decf9a1f1ba74f',
    messagingSenderId: '826399227870',
    projectId: 'rentykun',
    authDomain: 'rentykun.firebaseapp.com',
    storageBucket: 'rentykun.appspot.com',
    measurementId: 'G-HX4LGXXTE0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeIxDLyINf3vwVo8XiHlvlk0cz2XcLPe0',
    appId: '1:826399227870:android:e9dbf151a98a626c1ba74f',
    messagingSenderId: '826399227870',
    projectId: 'rentykun',
    storageBucket: 'rentykun.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_CF9fXPgq5NYDe6rOY9jNlcmah1M3DRY',
    appId: '1:826399227870:ios:2282625b402d56c71ba74f',
    messagingSenderId: '826399227870',
    projectId: 'rentykun',
    storageBucket: 'rentykun.appspot.com',
    iosBundleId: 'com.example.rentykun',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_CF9fXPgq5NYDe6rOY9jNlcmah1M3DRY',
    appId: '1:826399227870:ios:2282625b402d56c71ba74f',
    messagingSenderId: '826399227870',
    projectId: 'rentykun',
    storageBucket: 'rentykun.appspot.com',
    iosBundleId: 'com.example.rentykun',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPwXMkbbbLjH6iGf7w18yi0eGU5NDb1YY',
    appId: '1:826399227870:web:b70563d1903397a01ba74f',
    messagingSenderId: '826399227870',
    projectId: 'rentykun',
    authDomain: 'rentykun.firebaseapp.com',
    storageBucket: 'rentykun.appspot.com',
    measurementId: 'G-VBQKRZZGTP',
  );
}
